on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose Environemnt
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy on
        run: echo "hello from ${{inputs.environment}}"
