on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4.2.2
        - name: run tests
          run: |
            composer install --prefer-dist --no-scripts --no-progress --no-interaction
            php artisan test


